"""Append download columns

Revision ID: 1b1ae111bc4f
Revises: 3043e24cb141
Create Date: 2018-02-23 17:28:50.852959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1ae111bc4f'
down_revision = '3043e24cb141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('upload_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acts', 'upload_date')
    # ### end Alembic commands ###
