"""Append download columns

Revision ID: 3043e24cb141
Revises: b8f0e12084bb
Create Date: 2018-02-23 16:02:36.899595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3043e24cb141'
down_revision = 'b8f0e12084bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('download_date', sa.String(length=8), nullable=True))
    op.add_column('acts', sa.Column('is_download', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acts', 'is_download')
    op.drop_column('acts', 'download_date')
    # ### end Alembic commands ###
