"""Append act_date to table

Revision ID: 711e3f94f9c6
Revises: 1b1ae111bc4f
Create Date: 2018-09-30 21:42:59.932947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711e3f94f9c6'
down_revision = '1b1ae111bc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('act_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acts', 'act_date')
    # ### end Alembic commands ###
