"""empty message

Revision ID: 8973b513f1ac
Revises: 13b6fcfab473
Create Date: 2017-04-27 15:38:24.549087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8973b513f1ac'
down_revision = '13b6fcfab473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('parent_act', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'acts', 'acts', ['parent_act'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'acts', type_='foreignkey')
    op.drop_column('acts', 'parent_act')
    # ### end Alembic commands ###
