"""empty message

Revision ID: f007fdc5b185
Revises: 914aa966e9a6
Create Date: 2017-05-02 16:16:02.378073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f007fdc5b185'
down_revision = '914aa966e9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables_from_acts', sa.Column('time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables_from_acts', 'time')
    # ### end Alembic commands ###
